---
- name: add apt key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: add Jenkins repo
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present update_cache=yes

- name: install git
  apt: name=git state=present

- name: install Jenkins
  apt: name=jenkins state=latest

- name: enable and start Jenkins service
  service: name=jenkins state=started enabled=yes

- name: install pip
  apt: name=python-pip state=present

- name: install jenkins-job-builder
  pip: name=git+https://git.openstack.org/openstack-infra/jenkins-job-builder#egg=jenkins_job_builder state=present

- name: install workflow-aggregator plugin
  shell: java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://127.0.0.1:8080/ install-plugin workflow-aggregator --username admin --password `cat /var/lib/jenkins/secrets/initialAdminPassword`

- name: install git plugin
  shell: java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://127.0.0.1:8080/ install-plugin git --username admin --password `cat /var/lib/jenkins/secrets/initialAdminPassword`

- name: get password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: password

- name: create ~/.config/jenkins_jobs/
  file: state=directory dest=/var/lib/jenkins/.config/jenkins_jobs owner=jenkins group=jenkins

- name: put a jenkins job builder config file
  template: src=jenkins_jobs.ini dest=/var/lib/jenkins/.config/jenkins_jobs/jenkins_jobs.ini
