---
- name: download repo information
  get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

- name: import repo key
  rpm_key: key=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: install Jenkins
  yum: name=jenkins state=present

- name: put Jenkins config
  template: src=sysconfig-jenkins dest=/etc/sysconfig/jenkins mode=0600 backup=yes

- name: create {{ jenkins_home }}
  file: state=directory dest={{ jenkins_home }} owner=jenkins group=jenkins

- name: enable and start Jenkins service
  service: name=jenkins state=started enabled=yes

- name: install pip
  yum: name=python2-pip state=present

- name: install libyaml-devel
  yum: name=libyaml-devel state=present

- name: install jenkins-job-builder
  pip: name=git+https://git.openstack.org/openstack-infra/jenkins-job-builder#egg=jenkins_job_builder state=present

- name: install workflow-aggregator plugin
  shell: java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://127.0.0.1:{{ jenkins_port }}/ install-plugin workflow-aggregator --username admin --password `cat {{ jenkins_home }}/secrets/initialAdminPassword`

- name: get password
  shell: cat {{ jenkins_home }}/secrets/initialAdminPassword
  register: password

- name: create /etc/jenkins_jobs/
  file: state=directory dest=/etc/jenkins_jobs owner=jenkins group=jenkins

- name: put a jenkins job builder config file
  template: src=jenkins_jobs.ini dest=/etc/jenkins_jobs/jenkins_jobs.ini
